### ISSUE TITLE
Boost.Build fails cxx11_* tests when cross-compiling.

### ISSUE THREAD

**Issue by ClaymorePT** [boostorg/build#147]
If I try to cross-compile Boost.Fiber for the armv6 architecture, the cxx11_\* requirements in the Jamfile.v2 will fail, because the building system will try to execute the binaries on the host.

This should not happen.
The fact that the binaries are compiled should be enough to guarantee the cxx11_\* support by the compiler.

**Comment by swatanabe** [comment]
This should go to Boost.Config, as that is where these tests live.

**Comment by ClaymorePT** [comment]
@swatanabe 
Better late than never 👍 :)
