### ISSUE TITLE
no longer works with Visual Studio 2017 (VS15) preview 5

### ISSUE THREAD

**Issue by mircolino** [boostorg/build#148]
Installation directories are now:
VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\VS15 Preview 5\Common7\IDE\VisualCpp\
VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\VS15 Preview 5\Common7\Tools\

VCVARSALL.BAT is now located at:
C:\Program Files (x86)\Microsoft Visual Studio\VS15 Preview 5\Common7\IDE\VisualCpp\Auxiliary\Build\

**Comment by jhunold** [comment]
Won't fix this as the RC is out now. Patches for RC support welcome.
