### ISSUE TITLE
Bjam -j is capped at 256

### ISSUE THREAD

**Issue by brycelelbach** [boostorg/build#189]
./b2 -j268 does not work:

```
Invalid value for the '-j' option, valid values are 1 through 256.
```

I have more than 256 cores, I'd like to use them :)

**Comment by Belcourt** [comment]
Would 512 be sufficient for you for a while?

**Comment by swatanabe** [comment]
AMDG

On 04/01/2017 04:13 PM, Noel Belcourt wrote:
> Would 512 be sufficient for you for a while?
> 

  That's an easy change, but we really shouldn't
be using a fixed size array in the first place.

In Christ,
Steven Watanabe

**Comment by swatanabe** [comment]
AMDG

On 04/01/2017 04:13 PM, Noel Belcourt wrote:
> Would 512 be sufficient for you for a while?
> 

  For the record, the current limits imposed by the
implementation (other than the fact that cmdtab
is a static array) are:
execunix.c: FD_SETSIZE / 2 = 512
execnt.c: (MAXIMUM_WAIT_OBJECTS - 1) * MAXIMUM_WAIT_OBJECTS = 4032

In Christ,
Steven Watanabe

**Comment by swatanabe** [comment]
AMDG

...and actually, the limit is slightly less than 512,
because the b2 process has some file descriptors that
are not used for the child processes.  Just setting
MAXJOBS to 512 is definitely wrong.

In Christ,
Steven Watanabe

**Comment by phalexo** [comment]
I have spent a huge amount of time trying to build a C++ package through cmake. I have tried three different version of cmake v3.0.2 and to latest ones 3.9.0 and 2.8.x. 

Cmake passes -j 512 to b2 (building boost) for some reason. I don't know where the number is set.

Then cmake fails with the text below.  Is there any way to pass a different number to b2 from cmake?

Thanks 

[ 75%] Performing build step for 'Boost-system'
Invalid value for the '-j' option, valid values are 1 through 256.
make[2]: *** [Boost-system-prefix/src/Boost-system-stamp/Boost-system-build] Error 1
make[1]: *** [CMakeFiles/Boost-system.dir/all] Error 2
make: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /home/miner/.hunter/_Base/d4216c8/a7c3072/66a707b/Build/Boost/__system
[hunter ** FATAL ERROR **] [Directory:/home/miner/.hunter/_Base/Download/Hunter/0.19.14/d4216c8/Unpacked/cmake/projects/Boost/system]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at /home/miner/.hunter/_Base/Download/Hunter/0.19.14/d4216c8/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /home/miner/.hunter/_Base/Download/Hunter/0.19.14/d4216c8/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  /home/miner/.hunter/_Base/Download/Hunter/0.19.14/d4216c8/Unpacked/cmake/modules/hunter_download.cmake:596 (hunter_fatal_error)
  /home/miner/.hunter/_Base/Download/Hunter/0.19.14/d4216c8/Unpacked/cmake/projects/Boost/system/hunter.cmake:16 (hunter_download)
  /home/miner/.hunter/_Base/Download/Hunter/0.19.14/d4216c8/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:87 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/home/miner/ethminer/build/CMakeFiles/CMakeOutput.log".

**Comment by swatanabe** [comment]
AMDG

On 07/21/2017 06:03 PM, phalexo wrote:
> I have spent a huge amount of time trying to build a C++ package through cmake. I have tried three different version of cmake v3.0.2 and to latest ones 3.9.0 and 2.8.x. 
> 
> Cmake passes -j 512 to b2 (building boost) for some reason. I don't know where the number is set.
> 
> Then cmake fails with the text below.  Is there any way to pass a different number to b2 from cmake?
> 

  I have no idea.  Why don't you ask whoever wrote the
cmake code in question?  In any case, the cap for -j
has been lifted for the next release.

In Christ,
Steven Watanabe
