### ISSUE TITLE
No output's produced until an action completes

### ISSUE THREAD

**Issue by twesterhout** [boostorg/build#210]
Currently, output of commands called in `actions` is buffered and not displayed until a command completes (either finished successfully or fails). See also this discussion on the boost-dev mailing list:
http://boost.2283326.n4.nabble.com/build-No-output-until-an-action-completes-td4696541.html

It would be nice to have an option to turn buffering off and see the output immediately.

**Comment by swatanabe** [comment]
Actually, the output is not displayed at all if the command succeeds unless you pass -d2.
I was considering making early output the default for -j1, but obviously that would cause a change in behavior.
