### ISSUE TITLE
Command line option to ignore the site-config.jam

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/build#247]
This command line switch is needed to allow package managers to create 100% controlled, deterministic, reproducible builds.

**Comment by vinniefalco** [comment]
Attn: @ras0219-msft

**Comment by swatanabe** [comment]
AMDG

On 10/01/2017 11:27 AM, Vinnie Falco wrote:
> This command line switch is needed to allow package managers to create 100% controlled, deterministic, reproducible builds.
> 
> 

It's undocumented, but it actually does exist:

--ignore-site-config

Note: the reason I haven't documented this is
that each config files has a different method
for disabling it.  It should really be unified.

In Christ,
Steven Watanabe
