### ISSUE TITLE
?= not explained in the documentation.

### ISSUE THREAD

**Issue by ShimmerFairy** [boostorg/build#344]
While I have a guess as to what it means (assigns to the variable if it's empty), I want to check the documentation to make sure. However, [section 11.2.6 of the online documentation](https://boostorg.github.io/build/manual/develop/index.html#jam.language.variables) shows off that `?=` exists without ever explaining it. In fact, `?=` doesn't show up anywhere else in the entire manual, much less get explained.

Right now I'm trying to look at the code of boost build itself to try and find out what the answer is, but it's not that easy to find.

**Comment by grisumbras** [comment]
The section does explain what it does in the very paragraph that follows that snippet

>The final two forms are synonymous: they set variable globally, but only if it was previously unset.
