### ISSUE TITLE
The output of `common.copy` (from installing) sometimes appears and sometimes doesn't

### ISSUE THREAD

**Issue by pdimov** [boostorg/build#348]
Why is that, and can it be controlled?

**Comment by swatanabe** [comment]
AMDG

On 10/05/2018 07:02 AM, Peter Dimov wrote:
> Why is that, and can it be controlled?
> 

By output, do you mean:
     1 file(s) copied.

I'm not aware of anything that should suppress this.

In Christ,
Steven Watanabe

**Comment by pdimov** [comment]
My mistake. The actions of mine that don't appear use the `generate` rule to create the file directly in its installed place, not the `install` rule. So it's my `generate` actions that are silent, not `common.copy` (which is in fact overly verbose when it comes to installing the headers. :-) )
