### ISSUE TITLE
Call rule with an empty list as the second argument

### ISSUE THREAD

**Issue by Kojoley** [boostorg/build#386]
MWE:
```
# define rule that accepts list as the first and second arguments
rule llvm-config ( options * : components * )
{
    echo "option=$(options) component=$(components)" ;
}

llvm-config cxxflags ;
llvm-config ldflags : ;
llvm-config libs : engine ;
```

Output:
```


option=libs component=engine
```

Expected:
```
option=cxxflags
option=ldflags
option=libs component=engine
```

Am I doing something wrong or this is not supported? The documentation includes such a rule `rule create-file-from-another ( targets * : sources * : properties * )`.

**Comment by grisumbras** [comment]
`components` list is empty, any expansion involving it results in an empty list. What you probably want to do is 
`echo "option=$(options)" "component=$(components)" ;`

**Comment by Kojoley** [comment]
I corrected example, but the problem is that `options` is empty when rule called with empty `components`.

**Comment by grisumbras** [comment]
So, corrected rule still produces the same output?

**Comment by Kojoley** [comment]
Thanks, the problem was really with my Jam understanding.
