### ISSUE TITLE
Add support for VS 2019?

### ISSUE THREAD

**Issue by pdimov** [boostorg/build#389]
It has officially been announced that VS 2019 will be toolset version v142, cl.exe version 14.2x.xxxx; this should correspond to b2 toolset msvc-14.2.

@mloskot reports that from a 2019 developer command prompt, it already works and is being detected as msvc-14.1.

On a related note, I'm not sure what function `exact_version` is supposed to have here:

https://github.com/boostorg/build/blob/develop/src/tools/msvc.jam#L1178

but it's probably not being set because msvc-14.1 is at version 14.16.xxxx now.

**Comment by mloskot** [comment]
<script src="https://gist.github.com/mloskot/4d34a6f6d0e60a543f2ed153af87dcd9.js"></script>

**Comment by SpareSimian** [comment]
What version should be used for VS 2019? I'm seeing conflicting numbers in the version string, both 14.20 and 19.20:

c:\MSVS16\VC\Tools\MSVC\14.20.27404\bin\Hostx64\x64>cl.exe -?
Microsoft (R) C/C++ Optimizing Compiler Version 19.20.27404 for x64

**Comment by swatanabe** [comment]
AMDG

On 3/10/19 11:26 AM, SpareSimian wrote:
> What version should be used for VS 2019? I'm seeing conflicting numbers in the version string, both 14.20 and 19.20:
> 
> c:\MSVS16\VC\Tools\MSVC\14.20.27404\bin\Hostx64\x64>cl.exe -?
> Microsoft (R) C/C++ Optimizing Compiler Version 19.20.27404 for x64
> 

msvc-14.2

In Christ,
Steven Watanabe

**Comment by SpareSimian** [comment]
Why 14.2? What's the source for that number? I haven't found it in Microsoft documentation or in the output of the tools.

**Comment by mloskot** [comment]
> Why 14.2? What's the source for that number? 

The [MSVC Toolset Version](https://devblogs.microsoft.com/cppblog/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2017/)

VS2015 -> v140 (14.00) -> msvc=14.0
VS2017 -> v141 (14.1x) -> msvc=14.1
VS2019 -> v142 (14.2x) -> msvc=14.2

where `v142` is the [new toolset in VS2019](https://devblogs.microsoft.com/cppblog/cpp-binary-compatibility-and-pain-free-upgrades-to-visual-studio-2019/)

**Comment by swatanabe** [comment]
1.70 will have support for VS2019.

**Comment by PrabhathJ** [comment]
Does this mean boost 1.70 officially supports VS2019 ?

**Comment by jurko-gospodnetic** [comment]
1.72 notes still don't list 14.2 as officially supported 😕 
https://www.boost.org/users/history/version_1_72_0.html

**Comment by mloskot** [comment]
@jurko-gospodnetic 
>  the test suite results at https://www.boost.org/development/tests/master/developer/summary.html don't show any 14.2 toolset version numbers

This likely means there is no test machine provided (volunteered!) with VS2019 (msvc-14.2) available.

The release notes issue seem to be an overlook. @grafikrobot may know for sure.

**Comment by 4elovek37** [comment]
So is it correct that it is possible to freely use boost 1.70 and later with MSVC 14.2?
