### ISSUE TITLE
Is it possible to make a `run` test that always runs?

### ISSUE THREAD

**Issue by pdimov** [boostorg/build#390]
To take `run something.cpp ; explicit something ;` for example, we want `b2 something` to run the test even if a previous such invocation already ran it.

`alias always-run ; always always-run ; run something.cpp always-run ;` doesn't work.

`always [ run something.cpp ] ;` doesn't work either.

**Comment by swatanabe** [comment]
AMDG

On 2/3/19 10:05 AM, Peter Dimov wrote:
> To take `run something.cpp ; explicit something ;` for example, we want `b2 something` to run the test even if a previous such invocation already ran it.
> 
> `alias always-run ; always always-run ; run something.cpp always-run ;` doesn't work.
> 

This doesn't work, because an empty alias has nothing to build.

> `always [ run something.cpp ] ;` doesn't work either.
> 

It's a bug.

In Christ,
Steven Watanabe
