### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by cup** [boostorg/build#413]
I went here:

https://github.com/boostorg/build

and here:

https://github.com/boostorg/build/releases

and here:

https://boostorg.github.io/build

and i dont see where the "b2" executable can be downloaded

**Comment by swatanabe** [comment]
AMDG

On 3/18/19 8:08 AM, Steven Penny wrote:
> I went here:
> 
> https://github.com/boostorg/build
> 
> and here:
> 
> https://github.com/boostorg/build/releases
> 
> and here:
> 
> https://boostorg.github.io/build
> 
> and i dont see where the "b2" executable can be downloaded
> 

Build it from source:

https://boostorg.github.io/build/manual/develop/index.html#bbv2.installation

In Christ,
Steven Watanabe
