### ISSUE TITLE
Testing of Boost Build fails on Windows if .o is object file extension 

### ISSUE THREAD

**Issue by eldiener** [boostorg/build#472]
A number of tests of Boost Build on Windows fail if the toolset chosen to be used for the test creates a .o object file extension instead of a .obj object file extension. A Windows compiler which creates a .o object file extension is mingw-w64/gcc.

**Comment by swatanabe** [comment]
AMDG

On 8/26/19 8:32 AM, Edward Diener wrote:
> A number of tests of Boost Build on Windows fail if the toolset chosen to be used for the test creates a .o object file extension instead of a .obj object file extension. A Windows compiler which creates a .o object file extension is mingw-w64/gcc.
> 

There is code that is supposed to handle this here:
https://github.com/boostorg/build/blob/develop/test/BoostBuild.py#L134

In Christ,
Steven Watanabe
