### ISSUE TITLE
Boost compilation fails with too many input files on AIX7.2

### ISSUE THREAD

**Issue by bergen288** [boostorg/build#613]
I am trying to compile boost_1_73_0 on my AIX7.2 server. The default compiler is gcc8.3.0. However, bootstrap.sh says gcc doesn't support C++11 while it also gives list of toolsets including gcc.  See attached bootstrap.log.
[bootstrap.log](https://github.com/boostorg/boost/files/4713375/bootstrap.log)

If I run build.sh inside tools/build/src/engine, it won't complain about gcc, but it gives me "cpp: fatal error: too many input files". 
```r
> cpp -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jambase.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp execunix.cpp fileunix.cpp pathunix.cpp -o b2
cpp: fatal error: too many input files
compilation terminated.
```
Can you please help me to figure out what's wrong? 
[build.log](https://github.com/boostorg/boost/files/4713381/build.log)

**Comment by bergen288** [comment]
duplicate.

**Comment by bemehiser** [comment]
Duplicate of https://github.com/boostorg/build/issues/614

**Comment by PositiveTom** [comment]
i also ran into this problem. how do you solve this problem now?

**Comment by janwilmans** [comment]
workaround: https://github.com/bfgroup/b2/issues/323#issuecomment-1592899069
