### ISSUE TITLE
warning: No toolsets are configured (on FreeBSD)

### ISSUE THREAD

**Issue by yurivict** [boostorg/build#665]
While trying to update the FreeBSD port devel/boost_build, I encountered this problem:

./bootstrap.sh succeeds, but ```./b2 install --prefix=${STAGEDIR}${PREFIX}``` fails:
```
warning: No toolsets are configured.
warning: Configuring default toolset "gcc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
/usr/ports/devel/boost_build/work/build-4.3.0/src/tools/gcc.jam:226: in gcc.init from module gcc
error: toolset gcc initialization:
error: no command provided, default command 'g++' not found
```

clang should be default on FreeBSD.

README/bootstrap.sh say nothing about how to choose toolset.

How to fix the 'install' step?

**Comment by fasxmut** [comment]
You can do it like this:
b2 toolset=clang

And an alt choice if you are writing your own's project, add this line at the top of your Jamfile:
using clang ;

**Comment by yurivict** [comment]
b2 should have the clang toolset set as default on FreeBSD because FreeBSD uses clang as its main compiler.

**Comment by fasxmut** [comment]
> b2 should have the clang toolset set as default on FreeBSD because FreeBSD uses clang as its main compiler.

I am a freebsd user too, and new to b2. I started learning b2 building system few days ago, just found b2 is very simple and powerful. B2 uses many rewritable module files to store many rules. They are located at /usr/local/share/boost-build/src/ , the toolset setting can be programmed too.
