### ISSUE TITLE
clang -finline-functions

### ISSUE THREAD

**Issue by mnbittorrent** [boostorg/build#68]
With clang 3.6, there is a new warning for the -finline-functions flag. This should be removed from clang settings.

    clang: warning: optimization flag '-finline-functions' is not supported
    clang: warning: argument unused during compilation: '-finline-functions'

See http://stackoverflow.com/questions/26108606/no-support-to-finline-functions-in-clang-3-5

    clang --version
    Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
    Target: x86_64-apple-darwin14.1.0
    Thread model: posix

**Comment by vprus** [comment]
Is this not already solved inhttps://github.com/boostorg/build/commit/c2529b667ada26efd5ac320903012ef20efc119e ?

**Comment by mnbittorrent** [comment]
Not quite. The same thing will have to be done for clang-darwin.jam instead of clang-linux.jam.

**Comment by vprus** [comment]
True. Done in d20dad8
