### ISSUE TITLE
python_for_extensions should use -undefined dynamic_lookup on darwin

### ISSUE THREAD

**Issue by tdsmith** [boostorg/build#69]
build/src/tools/python.jam says:

>    # Unlike most *nix systems, Mac OS X's linker does not permit undefined
    # symbols when linking a shared library. So, we still need to link against
    # the Python framework, even when building extensions.

Passing `-undefined dynamic_lookup` to the linker (instead of -lpython or -framework Python) permits undefined symbols and achieves the desired behavior. This has existed [since OS X 10.1](http://www.cmake.org/pipermail/cmake/2005-March/006249.html) so there should be no compatibility concerns.

Linking a module against one Python framework and importing it from another (ABI-compatible) interpreter causes the interpreter to segfault, so the current behavior is a pain point for e.g. Homebrew.

**Comment by asparagui** [comment]
What he said.

**Comment by vprus** [comment]
Anybody can submit a pull request, along with comment how it was tested?
While the change seem simple, I'd rather not commit things I can't test.

Thanks,

**Comment by vprus** [comment]
Tim,

did you have a time to create a patch?

**Comment by tdsmith** [comment]
I hadn't tried but I think I see how to do it. I don't have a boost development environment set up. I propose to test by making this change in the latest boost release tarball, build Boost.Python, and demonstrate that an application that uses Boost.Python still functions despite the different linkage.

**Comment by tdsmith** [comment]
Done in #78.

**Comment by tdsmith** [comment]
Closed by b1c031d26b0e94570511acfdb0dfb8a43f0f6e58 (thanks!).
